# Generated by Django 4.0.5 on 2022-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='municipality',
            new_name='city',
        ),
        migrations.AddField(
            model_name='listings',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='listings',
            name='area',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Outside India', 'Outside India')], max_length=20, null=True),
        ),
    ]
