# Generated by Django 4.0.5 on 2022-07-05 11:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
